CREATE TABLE public.article (
 id UUID PRIMARY KEY,
 slug VARCHAR(255) NOT NULL UNIQUE,
 title VARCHAR(255) NOT NULL UNIQUE,
 content VARCHAR(255) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
